### PR TITLE
[issue 1] maybe this fixes the mac error?

### PR DESCRIPTION
**Pull request by mankins**
I had this problem on osx too with sed. It's been too long since I did sed work, but this seems to solve the problem for me at the expense of adding perl to the mix. I'm sure there's a better way to fix it, but sending in case others find it useful temporarily.

### CODE REVIEW

**Comment by mulka** [comment]
This change worked for me on my mac

**Comment by coreylight** [comment]
@ewindisch look into this?

**Comment by ewindisch** [comment]
I have a NodeJS based version I'll create a PR for. I'm not keen on relying on Perl _and_ sed. I could fix the sed command, but it's kinda system dependent... and the current solution's not very reliable, anyway.

**Comment by pselle** [comment]
Closing, looking for a Node.js based version @ewindisch

**Pull request closed without merging**
